<?
$ADMIN_NAME = "이강석";
$COMPANY_NAME = "BOB Mart";
$ADMIN_TEL = "";
$ADMIN_EMAIL = "system@daum.net";
$ADMIN_TITLE = "BOB Mart";
$ADMIN_TITLE_E = "BOB Mart";
$COMPANY_BUSINESS_NUM = "121-13-57924";
$COMPANY_CEO = "BOB Mart";
$CUSTOMER_TEL = "02-20234-18373";
$CUSTOMER_FAX = "010-20234-18373";
$COMPANY_ADD = "서울 영등포구 의사당대로 100";
$COMPANY_BUSINESS_TYPE = "";
$COMPANY_BUSINESS_CONDITION = "";
$COMPANY_COMMUNICATION_NUM = "";
$SITE_URL = "http://localhost/shop";
$HOME_TITLE = "";
$HOME_DESCRIPTION = "";
$HOME_KEYWORD = "BOB Mart";
$HOME_REFKEYWORD = "";
$SOURCEPROTECTION = "";
$DENYIP = "";
$ALLOWFORADMIN = "1|";
$SYSTEM_HDD_SIZE = "100";
$SYSTEM_DB_SIZE = "50";
?>