<?
$MEMBER_GRADE_NAME[1] = "최고관리자";
$MEMBER_GRADE_NAME[2] = "";
$MEMBER_GRADE_NAME[3] = "";
$MEMBER_GRADE_NAME[4] = "";
$MEMBER_GRADE_NAME[5] = "기업회원";
$MEMBER_GRADE_NAME[6] = "";
$MEMBER_GRADE_NAME[7] = "";
$MEMBER_GRADE_NAME[8] = "";
$MEMBER_GRADE_NAME[9] = "";
$MEMBER_GRADE_NAME[10] = "일반회원";
?>