<?php

# ByteHoard2 Configuration file
# Generated at Monday 29th 2015f June 2015 10:49:32 AM [1435542572]
# Generated by ByteHoard 2.1 Zeta
# ByteHoard2 is released under the GPL.
# http://www.bytehoard.org

$dbconfig['host'] = "localhost";
$dbconfig['username'] = "root";
$dbconfig['password'] = "bobmartbobmart";
$dbconfig['db'] = "webhard";
$dbconfig['prefix'] = "fsec_";
$dbconfig['dbmod'] = "mysql.inc.php";
$dbconfig['type'] = "mysql";


?>
